version: '3'
services:
    db:
        image: 'postgres:latest'
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: postgres
            POSTGRES_DB: cert-imoveis
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"